# Generated by Django 5.0 on 2024-03-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Search",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=200)),
                ("answer", models.TextField()),
                ("reference", models.URLField()),
                ("image", models.ImageField(null=True, upload_to="images/")),
            ],
        ),
        migrations.DeleteModel(
            name="Item",
        ),
    ]
